AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  want-list

  Sample SAM Template for want-list

# Parameters:
#     Env:
#         Type: String
#         Default: local

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  # Environment:
  #   Variables:
  #     ENV: !Ref Env

Resources:
  GetAllFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: resources/get_all
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref WantlistTable
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get_all
            Method: get
  SearchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: resources/search
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref WantlistTable
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /search
            Method: get
  RegisterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: resources/register
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref WantlistTable
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /register
            Method: post

  WantlistTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WantListTable
      AttributeDefinitions:
        - AttributeName: jan
          AttributeType: S
      KeySchema:
        - AttributeName: jan
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetAllApi:
    Description: "API Gateway endpoint URL for Prod stage for Get all function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_all/"
  GetAllFunction:
    Description: "Get all Lambda Function ARN"
    Value: !GetAtt GetAllFunction.Arn
  GetAllFunctionIamRole:
    Description: "Implicit IAM Role created for Get all function"
    Value: !GetAtt GetAllFunctionRole.Arn

  SearchApi:
    Description: "API Gateway endpoint URL for Prod stage for Search function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/search/"
  SearchFunction:
    Description: "Search Lambda Function ARN"
    Value: !GetAtt SearchFunction.Arn
  SearchFunctionIamRole:
    Description: "Implicit IAM Role created for Search function"
    Value: !GetAtt SearchFunctionRole.Arn

  RegisterApi:
    Description: "API Gateway endpoint URL for Prod stage for Register function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/register/"
  RegisterFunction:
    Description: "Register Lambda Function ARN"
    Value: !GetAtt RegisterFunction.Arn
  RegisterFunctionIamRole:
    Description: "Implicit IAM Role created for Register function"
    Value: !GetAtt RegisterFunctionRole.Arn
